# Generated by Django 2.1.4 on 2019-01-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190119_1237'),
        ('management', '0002_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(auto_created=True, null=True)),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('phone', models.IntegerField(verbose_name='电话号码')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('depart', models.ForeignKey(on_delete=True, to='management.Depart', verbose_name='部门')),
                ('roles', models.ManyToManyField(to='rbac.Role', verbose_name='用户的角色')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
