# Generated by Django 2.1.4 on 2019-01-20 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='create_data',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='miao', max_length=16, verbose_name='真名'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
